before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y npm nodejs libid3-dev
language: c
compiler:
    - clang
    - gcc
script: npm install node-gyp && ./build.sh
notifications:
  email:
    recipients:
      - jess.portnoy@kaltura.com
    on_success: change
    on_failure: always
